### PR TITLE
timeout handling

### PR DESCRIPTION
**Pull request by ghost**
-Add routed request to hashmap before starting timeout timer
-Delete request on timeout event if not found in request hashmap

### CODE REVIEW

**Comment by ghost** [comment]
Hallo Stephan,

ein gutes Neues Jahr wünsche ich Dir!

Beim Betrachten der timeout-Behandlung sind mir zwei Sachen aufgefallen.

hoffentlich bis bald,
Matthias

**Review by gatzka — COMMENTED** [review]
Do you have a unit test where the old behavior (especially in request_timeout_handler) leads to wrong results or memory leaks. The latter should be the case because cjet_free was called only in some cases.

**Comment by ghost** [comment]
Hi Stephan,

no, there are no tests yet. Yesterday I came over this. I need time for testing...

**Comment by ghost** [comment]
are there any existing tests for transactions I can copy stuff from?

**Comment by gatzka** [comment]
Sure. for instance in src/tests/state_test.cpp there are test for "set" which should cover the code arming and disarming the timer.

**Comment by ghost** [comment]
I'm confused, if I understand correctly, it is either request_timeout_handler or handle_routing_response being called depending on whether timeout or not.

Why are there different ways being used to lookup the request in the hash table?

**Comment by ghost** [comment]
I simplified this a bit more.

Please have a look at HASHTABLE_REMOVE

Still no unit test.

**Comment by ghost** [comment]
Still struggling to create a unit test. I added some documentation.

**Comment by ml-bb** [comment]
Ok, @gatzka how about merging this one? Yes, there are no additional tests. But I think some handling is simplified and cleaner.

**Review by MarioMolitor — APPROVED** [review]

**Pull request merged**
